name: Interactive Workflow
on:
  workflow_dispatch:
    inputs:
      application_type:
        description: 'What type of application are you building?'
        required: true
		options: [Backend-API, Server]
      schema_path:
        description: 'Where is your schema?: (path or url)'
      pick_plugins:
        description: 'Pick plugins:'
		required: true
		options: [TypeScript (required by other typescript plugins), TypeScript Resolvers (strongly typed resolve functions)']
	  output_path:
		description: 'Where to write the output:'
	  Introspection-file:
	    description: 'Do you want to generate an introspection file?'
		required: true
		options: [Yes, No]
	  Configfile_name:
	    description: 'How to name the config file?'
	  script_run:
	    description: 'What script in package.json should run the codegen?'
