name: Interactive Workflow

on: [push]

jobs:
  interactive_job:
    runs-on: ubuntu-latest

    steps:
      - name: Ask for favorite color
        id: color_input
        run: |
          echo "What is your favorite color?"
          echo "::set-output name=color::$(read -r color && echo $color)"

      - name: Ask Yes/No question
        id: proceed_input
        run: |
          echo "Do you want to proceed? (yes/no)"
          echo "::set-output name=proceed::$(read -r proceed && echo $proceed)"

      - name: Ask for additional comments
        id: comments_input
        run: |
          echo "Please enter additional comments:"
          echo "::set-output name=comments::$(read -r comments && echo $comments)"

      - name: Display inputs
        run: |
          echo "Favorite color: ${{ steps.color_input.outputs.color }}"
          echo "Proceed choice: ${{ steps.proceed_input.outputs.proceed }}"
          echo "Additional comments: ${{ steps.comments_input.outputs.comments }}"
